MyBlog/Models/Home/HomeIndexViewModel.cs
using MyBlog.Models.ArticleModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBlog.Models.Home
{
    public class HomeIndexViewModel
    {
		public List<Article> Articles { get; set; }
		public PageViewModel PageViewModel { get; set; }
	}
}

MyBlog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBlog.Models;
using MyBlog.Models.ArticleModels;

namespace MyBlog.Controllers
{
	public class ArticleController : Controller
    {
		private readonly ApplicationContext db;

		public ArticleController(ApplicationContext db)
		{
			this.db = db;
		}

		public async Task<IActionResult> Index(int? id)
		{
			if (id != null)
			{
				Article article = await db.Articles.FirstOrDefaultAsync(a => a.Id == id);
				if (article != null)
				{
					return View(article);
				}
			}

			return NotFound();
		}

		public IActionResult Create()
        {
			return View();
        }

		[HttpPost]
		public async Task<IActionResult> Create(Article article)
		{
			if (ModelState.IsValid)
			{
				if (article.FormFile != null)
				{
					using (BinaryReader binaryReader = new BinaryReader(article.FormFile.OpenReadStream()))
					{
						article.Photo = binaryReader.ReadBytes((int)article.FormFile.Length);
					}
				}
				else
				{
					using (FileStream fs = new FileStream("wwwroot/images/default.jpeg", FileMode.OpenOrCreate))
					{
						using (BinaryReader binaryReader = new BinaryReader(fs))
						{
							article.Photo = binaryReader.ReadBytes((int)fs.Length);
						}
					}
				}
				db.Articles.Add(article);
				await db.SaveChangesAsync();
				return RedirectToAction("Index", "Home");
			}

			return View(article);
		}

		[HttpGet]
		[ActionName("Delete")]
		public async Task<IActionResult> ConfirmDelete(int? id)
		{
			if (id != null)
			{
				Article article = await db.Articles.FirstOrDefaultAsync(a => a.Id == id);
				if (article != null)
				{
					return View(article);
				}
			}

			return NotFound();
		}

		[HttpPost]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id != null)
			{
				Article article = await db.Articles.FirstOrDefaultAsync(a => a.Id == id);
				if (article != null)
				{
					db.Articles.Remove(article);
					await db.SaveChangesAsync();
					return RedirectToAction("Index", "Home");
				}
			}

			return NotFound();
		}

		public async Task<IActionResult> Edit(int? id)
		{
			if (id != null)
			{
				Article article = await db.Articles.FirstOrDefaultAsync(a => a.Id == id);
				if (article != null)
				{
					return View(article);
				}
			}

			return NotFound();
		}

		[HttpPost]
		public async Task<IActionResult> Edit(Article article)
		{
			if (ModelState.IsValid)
			{
				if (article.FormFile != null)
				{
					using (BinaryReader binaryReader = new BinaryReader(article.FormFile.OpenReadStream()))
					{
						article.Photo = binaryReader.ReadBytes((int)article.FormFile.Length);
					}
				}
				db.Articles.Update(article);
				await db.SaveChangesAsync();
				return RedirectToAction("Index", "Home");
			}

			return View(article);
		}
    }
}

MyBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBlog.Models;
using MyBlog.Models.ArticleModels;
using MyBlog.Models.Home;

namespace MyBlog.Controllers
{
    public class HomeController : Controller
    {
		private readonly ApplicationContext db;

		public HomeController(ApplicationContext db)
		{
			this.db = db;
		}

		public IActionResult ErrorStatus(string id)
		{
			return View("ErrorStatus", id);
		}

		private string CutText(string text, int length)
		{
			text = text.Substring(0, length);
			int indexLastWord = text.LastIndexOf(' ');
			text = text.Remove(indexLastWord);
			text += "...";

			return text;
		}

		public async Task<IActionResult> Index(string searchText, int page = 1)
        {
			int pageSize = 4;
			IQueryable<Article> articles = db.Articles.OrderByDescending(a => a.Date);
			if (searchText != null)
			{
				searchText = searchText.ToLower();
				articles = articles.Where(a => a.Text.ToLower().Contains(searchText) || a.Title.ToLower().Contains(searchText));
			}			
			int count = articles.Count();
			List<Article> items = await articles.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
			foreach (Article article in items)
			{
				if (article.Text.Length > 200)
				{
					article.Text = CutText(article.Text, 200);
				}
			}
			PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
			HomeIndexViewModel viewModel = new HomeIndexViewModel
			{
				PageViewModel = pageViewModel,
				Articles = items,
			};
			ViewBag.searchText = searchText;

			return View(viewModel);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyBlog/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyBlog/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyBlog/Views/Home/ErrorStatus.cshtml
@model string
@{
    ViewData["Title"] = "ErrorStatus";
}
<style>
    html, body {
        height: 100%;
        overflow: hidden;
    }

    .error-page {
        display: flex;
        align-items: center;
        justify-content: center;
        text-align: center;
        height: 100%;
        font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
    }

        .error-page h1 {
            font-size: 30vh;
            font-weight: bold;
            position: relative;
            margin: -8vh 0 0;
            padding: 0;
        }

            .error-page h1:after {
                content: attr(data-h1);
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                color: transparent;
                /* webkit only for graceful degradation to IE */
                background: -webkit-repeating-linear-gradient(-45deg, #71b7e6, #69a6ce, #b98acc, #ee8176, #b98acc, #69a6ce, #9b59b6);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-size: 400%;
                text-shadow: 1px 1px 2px rgba(255, 255, 255, 0.25);
                animation: animateTextBackground 10s ease-in-out infinite;
            }

            .error-page h1 + p {
                color: #d6d6d6;
                font-size: 8vh;
                font-weight: bold;
                line-height: 10vh;
                max-width: 600px;
                position: relative;
            }

                .error-page h1 + p:after {
                    content: attr(data-p);
                    position: absolute;
                    top: 0;
                    left: 0;
                    right: 0;
                    color: transparent;
                    text-shadow: 1px 1px 2px rgba(255, 255, 255, 0.5);
                    -webkit-background-clip: text;
                    -moz-background-clip: text;
                    background-clip: text;
                }

    #particles-js {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }

    @@keyframes animateTextBackground {
        0% {
            background-position: 0 0;
        }

        25% {
            background-position: 100% 0;
        }

        50% {
            background-position: 100% 100%;
        }

        75% {
            background-position: 0 100%;
        }

        100% {
            background-position: 0 0;
        }
    }

    @@media (max-width: 767px) {
        .error-page h1 {
            font-size: 32vw;
        }

            .error-page h1 + p {
                font-size: 8vw;
                line-height: 10vw;
                max-width: 70vw;
            }
    }
</style>
<div class="error-page">
    <div>
        @if (Model == "400")
        {
            <h1 data-h1="400">400</h1>
            <p data-p="BAD REQUEST">BAD REQUEST</p>
        }
        @if (Model == "401")
        {
            <h1 data-h1="401">401</h1>
            <p data-p="UNAUTHORIZED">UNAUTHORIZED</p>
        }
        @if (Model == "403")
        {
            <h1 data-h1="403">403</h1>
            <p data-p="FORBIDDEN">FORBIDDEN</p>
        }
        @if (Model == "404")
        {
            <h1 data-h1="404">404</h1>
            <p data-p="NOT FOUND">NOT FOUND</p>
        }
        @if (Model == "500")
        {
            <h1 data-h1="500">500</h1>
            <p data-p="SERVER ERROR">SERVER ERROR</p>
        }
    </div>
</div>
<div id="particles-js"></div>
@section Scripts{
    <environment include="Development">
        <script src="~/lib/particles.js-master/particles.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src='https://cdnjs.cloudflare.com/ajax/libs/particles.js/2.0.0/particles.min.js'
                asp-fallback-src="~/lib/particles.js-master/particles.min.js">                
        </script>       
    </environment>
    <script src="js/error.js"></script>
}

MyBlog/Views/Home/Index.cshtml
@addTagHelper "*, MyBlog"
@model MyBlog.Models.Home.HomeIndexViewModel
@if (User.IsInRole("admin"))
{
    <div>
        <a class="btn btn-success create-acrticle-btn" asp-action="Create" asp-controller="Article">Create Article</a>
    </div>
}

<div class="home-index-wrapper">
    @foreach (var article in Model.Articles)
    {
    <div class="home-index-article-wrapper">
        <h2>
            <a class="article-title" asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">@article.Title</a>
        </h2>
       <figure class="caption-border">
            <img class="" alt="Alternate Text" src="data:image/jpeg;base64,@(Convert.ToBase64String(article.Photo))" />
            <figcaption>
                Date: @article.Date.DayOfWeek
                <em class="">@article.Date.ToShortDateString()</em>
            </figcaption>
        </figure>
        <p class="article-text">@article.Text</p>
        @if (User.IsInRole("admin"))
        {
            <a class="btn btn-danger" asp-action="Delete" asp-controller="Article" asp-route-id="@article.Id">Delete</a>
            <a class="btn btn-warning" asp-action="Edit" asp-controller="Article" asp-route-id="@article.Id">Edit</a>
        }
        <a class="btn btn-default article-readmore" asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">Read more</a>
    </div>
    }
</div>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>